[mypy]
python_version = 3.13
pretty = True
show_error_codes = True
warn_return_any = True
warn_unused_configs = True
exclude = (?x)(
    ^alembic/versions/
  | ^\.venv/
  )

# SQLAlchemy ships py.typed; keep plugin for ORM model checking.
plugins = sqlalchemy.ext.mypy.plugin

[mypy-alembic.*]
ignore_missing_imports = True
